### ISSUE TITLE
nms-1d-cpu importError

### ISSUE THREAD

**Issue by LeeRoc-China** [ttgeng233/UnAV#11]
when i execute `python setup.py install --user`
it happened like this:
```
running install
/sda/home/xxx/anaconda3/envs/UnAV/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/sda/home/xxx/anaconda3/envs/UnAV/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing nms_1d_cpu.egg-info/PKG-INFO
writing dependency_links to nms_1d_cpu.egg-info/dependency_links.txt
writing top-level names to nms_1d_cpu.egg-info/top_level.txt
/sda/home/xxx/anaconda3/envs/UnAV/lib/python3.10/site-packages/torch/utils/cpp_extension.py:387: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'nms_1d_cpu.egg-info/SOURCES.txt'
writing manifest file 'nms_1d_cpu.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-cpython-310/nms_1d_cpu.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for nms_1d_cpu.cpython-310-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/nms_1d_cpu.py to nms_1d_cpu.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying nms_1d_cpu.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nms_1d_cpu.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nms_1d_cpu.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nms_1d_cpu.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.nms_1d_cpu.cpython-310: module references __file__
creating 'dist/nms_1d_cpu-0.0.0-py3.10-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing nms_1d_cpu-0.0.0-py3.10-linux-x86_64.egg
creating /sda/home/xxx/.local/lib/python3.10/site-packages/nms_1d_cpu-0.0.0-py3.10-linux-x86_64.egg
Extracting nms_1d_cpu-0.0.0-py3.10-linux-x86_64.egg to /sda/home/xxx/.local/lib/python3.10/site-packages
Adding nms-1d-cpu 0.0.0 to easy-install.pth file
detected new path './nms_1d_cpu-0.0.0-py3.10-linux-x86_64.egg'

Installed /sda/home/xxx/.local/lib/python3.10/site-packages/nms_1d_cpu-0.0.0-py3.10-linux-x86_64.egg
Processing dependencies for nms-1d-cpu==0.0.0
Finished processing dependencies for nms-1d-cpu==0.0.0
```

and then when i try to train the model, other error happened:
```
Traceback (most recent call last):
  File "/sda/home/xxx/Program/UnAV/./train.py", line 18, in <module>
    from libs.modeling import make_multimodal_meta_arch
  File "/sda/home/xxx/Program/UnAV/libs/modeling/__init__.py", line 7, in <module>
    from . import multimodal_meta_archs
  File "/sda/home/xxx/Program/UnAV/libs/modeling/multimodal_meta_archs.py", line 12, in <module>
    from ..utils import batched_nms
  File "/sda/home/xxx/Program/UnAV/libs/utils/__init__.py", line 1, in <module>
    from .nms import batched_nms
  File "/sda/home/xxx/Program/UnAV/libs/utils/nms.py", line 5, in <module>
    import nms_1d_cpu
ImportError: /sda/home/xxx/.local/lib/python3.10/site-packages/nms_1d_cpu-0.0.0-py3.10-linux-x86_64.egg/nms_1d_cpu.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl
```

do you know why this?

**Comment by libaolong4473** [comment]
Sir，Have you solved this problem？

**Comment by libaolong4473** [comment]
删除/home/xxx/.local/lib/python3.8/site-packages/ 路径下与nms有关的文件，删除/home/xxx/UnAV/libs/utils/下的dist、build、nms_1d_cpu.egg-info文件夹。然后uninstall torch 并重新安装，再重新执行python setup.py install --user即可解决

**Comment by mortyzhou77** [comment]
> 删除/home/xxx/.local/lib/python3.8/site-packages/ 路径下与nms有关的文件，删除/home/xxx/UnAV/libs/utils/下的dist、build、nms_1d_cpu.egg-info文件夹。然后uninstall torch 并重新安装，再重新执行python setup.py install --user即可解决

大佬，请问“删除/home/xxx/.local/lib/python3.8/site-packages/ 路径下与nms有关的文件”主要包括了哪些内容呀？我碰到的问题一直是cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

这类问题。。感谢

**Comment by woxihuanshuijiao** [comment]
> 删除/home/xxx/.local/lib/python3.8/site-packages/ 路径下与nms有关的文件，删除/home/xxx/UnAV/libs/utils/下的dist、build、nms_1d_cpu.egg-info文件夹。然后uninstall torch 并重新安装，再重新执行python setup.py install --user即可解决

我按照这样的方法解决了ImportError的报错，感恩

**Comment by libaolong4473** [comment]
> > 删除/home/xxx/.local/lib/python3.8/site-packages/ 路径下与nms有关的文件，删除/home/xxx/UnAV/libs/utils/下的dist、build、nms_1d_cpu.egg-info文件夹。然后uninstall torch 并重新安装，再重新执行python setup.py install --user即可解决
> 
> 大佬，请问“删除/home/xxx/.local/lib/python3.8/site-packages/ 路径下与nms有关的文件”主要包括了哪些内容呀？我碰到的问题一直是cpp_extension.py", line 1756, in _run_ninja_build raise RuntimeError(message) from e RuntimeError: Error compiling objects for extension
> 
> 这类问题。。感谢

没做这方面的内容了，忘了怎么解决的了，sorry

**Comment by taleemnoser-pixel** [comment]
> > 删除/home/xxx/.local/lib/python3.8/site-packages/ 路径下与nms有关的文件，删除/home/xxx/UnAV/libs/utils/下的dist、build、nms_1d_cpu.egg-info文件夹。然后uninstall torch 并重新安装，再重新执行python setup.py install --user即可解决
> 
> 大佬，请问“删除/home/xxx/.local/lib/python3.8/site-packages/ 路径下与nms有关的文件”主要包括了哪些内容呀？我碰到的问题一直是cpp_extension.py“，第1756行，_run_ninja_build raise RuntimeError（message） from e RuntimeError： Error compiling objects for extension
> 
> 这类问题。。感谢

你好，我目前在运行此代码时也遇到了此问题，请问针对这个问题你知道该如何解决吗？
